# Default configurations for graph models

barabasi_albert:
  n: 50
  seq_len: 200
  min_segment: 40
  min_changes: 1
  max_changes: 2
  m: 1
  min_m: 1
  max_m: 6
  n_std: null
  m_std: null

watts_strogatz:
  n: 50
  seq_len: 200
  min_segment: 40
  min_changes: 1
  max_changes: 2
  k_nearest: 6
  min_k: 4
  max_k: 8
  rewire_prob: 0.1
  min_prob: 0.05
  max_prob: 0.15
  n_std: null
  k_std: 0.2
  prob_std: 0.01

erdos_renyi:
  n: 50
  seq_len: 200
  min_segment: 40
  min_changes: 1
  max_changes: 2
  prob: 0.05
  min_prob: 0.05
  max_prob: 0.4
  n_std: null
  prob_std: null

stochastic_block_model:
  n: 50
  seq_len: 200
  min_segment: 40
  min_changes: 2
  max_changes: 2
  num_blocks: 2
  min_block_size: 25
  max_block_size: 25
  intra_prob: 0.95
  inter_prob: 0.01
  min_intra_prob: 0.3
  max_intra_prob: 0.95
  min_inter_prob: 0.01
  max_inter_prob: 0.3
  n_std: null
  blocks_std: null
  intra_prob_std: null
  inter_prob_std: null
